### ISSUE TITLE
Multiple filters in one command

### ISSUE THREAD

**Issue by caesarshift** [kyz/libmspack#28]
When using cabextract on large cab files with many bundled files, the ability to extract more than one file based on multiple filters is a huge efficiency gain (minutes vs hours). However, I was not able to find a way to do it without breaking the existing API. So I'm submitting a feature request for your consideration vs. a pull request:

https://github.com/caesarshift/libmspack

**Comment by kyz** [comment]
Thanks for the useful suggestion!

I'm not sure what you mean about breaking the existing API. What would work perfectly well, I think, is the ability to supply more than one `-F` option, e.g. `cabextract -F *.mov -F *.avi foo.cab`

What do you think?

**Comment by caesarshift** [comment]
That sounds perfect! Chalk up the "breaking API" comment to my limited understanding of opt. If you look at my fork, you will see that the additional filters are being parsed as the "extra" args. Which is what cabextract normally sees as additional cab files. So my fork emits a warning that only the first file is seen as a cab file and all others are seen as filters. Your way is better and doesn't break that usage.

**Comment by kyz** [comment]
I  added the feature in commits c45f055 and cdcaeb9a445ba174dcc1adbf0777c83a3ee709f3 - please let me know if it works for you.

**Comment by caesarshift** [comment]
Thank you for your patience on testing. *Works perfectly.*

One note: when I tried to compile with the 1.9.1 makefile, gcc threw an error with the new code. If you've already adjusted the makefile for the next release, then ignore this.

Exact error:

```
gcc -DHAVE_CONFIG_H -I.  -I./mspack -DMSPACK_NO_DEFAULT_SYSTEM   -g -O2 -c -o src/cabextract.o src/cabextract.c
src/cabextract.c: In function ‘process_cabinet’:
src/cabextract.c:470:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (struct filter *f = args.filters; f; f = f->next) {
```

**Comment by kyz** [comment]
Thanks for testing. I fixed the issue you encountered in 56fe06f52403e7d19160767c6af060b2b528a2ff - I'd quite like to use C99 standards, but first I need to update the build scripts so they check for and turn on C99 mode. So I've shelved that for now, gone back to C89, and I'll look at C99 in the future.

**Comment by kyz** [comment]
This has been released in cabextract 1.10
